// ===========================================
// RpaWpfComponents/AdvancedDataGrid/Models/DataGridConfiguration.cs
// ===========================================
using RpaWpfComponents.AdvancedDataGrid.Models;
using System.Collections.Generic;

namespace RpaWpfComponents.AdvancedDataGrid.Models
{
    public class DataGridConfiguration
    {
        public List<ColumnDefinitionModel> Columns { get; set; } = new();
        public List<ValidationRuleModel> ValidationRules { get; set; } = new();
        public bool ShowMirrorEditor { get; set; } = true;
        public bool EnableAsyncValidation { get; set; } = true;
        public bool EnableKeyboardNavigation { get; set; } = true;
        public bool EnableClipboardOperations { get; set; } = true;
        public int InitialRowCount { get; set; } = 50;
        public bool AutoGenerateDeleteColumn { get; set; } = true;
        public bool AutoGenerateValidAlertsColumn { get; set; } = true;
    }
}